-- a. Truy vấn sử dụng INNER JOIN:
SELECT KH.HOTEN, HD.SOHD, HD.TRIGIA
FROM KHACHHANG KH
INNER JOIN HOADON HD ON KH.MAKH = HD.MAKH;
-- b. Truy vấn sử dụng OUTER JOIN:
SELECT KH.HOTEN, HD.SOHD, HD.TRIGIA
FROM HOADON HD
LEFT OUTER JOIN KHACHHANG KH ON HD.MAKH = KH.MAKH;
-- c. Sử dụng subquery trong điều kiện WHERE:
SELECT NV.HOTEN
FROM NHANVIEN NV
WHERE NV.MANV IN (SELECT HD.MANV FROM HOADON HD WHERE HD.TRIGIA > (SELECT AVG(TRIGIA) FROM HOADON)
);
-- d. Sử dụng subquery trong phần FROM:
SELECT KH.HOTEN, SUM(HD.TOTAL) AS TOTAL_PURCHASE
FROM KHACHHANG KH
JOIN (SELECT MAKH, SUM(TRIGIA) AS TOTAL FROM HOADON GROUP BY MAKH ) HD ON KH.MAKH = HD.MAKH
GROUP BY KH.HOTEN;
-- e. Truy vấn sử dụng GROUP BY và các hàm tổng hợp:
SELECT MANV, COUNT(SOHD) AS ORDERS, SUM(TRIGIA) AS TOTAL_SALES
FROM HOADON
GROUP BY MANV;