-- Tạo bảng log để lưu trữ thông tin thay đổi
CREATE TABLE HOADON_LOG (
    LOG_ID INT AUTO_INCREMENT PRIMARY KEY,
    SOHD INT,
    NGHD DATETIME,
    TRIGIA VARCHAR(20),
    ACTION_TYPE VARCHAR(20),
    TIMESTAMP DATETIME DEFAULT CURRENT_TIMESTAMP
);
DELIMITER $$

-- Trigger khi chèn (insert) một hóa đơn mới vào bảng HOADON
CREATE TRIGGER after_insert_hoadon
AFTER INSERT ON HOADON
FOR EACH ROW
BEGIN
    INSERT INTO HOADON_LOG (SOHD, NGHD, TRIGIA, ACTION_TYPE)
    VALUES (NEW.SOHD, NEW.NGHD, NEW.TRIGIA, 'INSERT');
END$$

-- Trigger khi cập nhật (update) một hóa đơn trong bảng HOADON
CREATE TRIGGER after_update_hoadon
AFTER UPDATE ON HOADON
FOR EACH ROW
BEGIN
    INSERT INTO HOADON_LOG (SOHD, NGHD, TRIGIA, ACTION_TYPE)
    VALUES (NEW.SOHD, NEW.NGHD, NEW.TRIGIA, 'UPDATE');
END$$

-- Trigger khi xóa (delete) một hóa đơn trong bảng HOADON
CREATE TRIGGER after_delete_hoadon
AFTER DELETE ON HOADON
FOR EACH ROW
BEGIN
    INSERT INTO HOADON_LOG (SOHD, NGHD, TRIGIA, ACTION_TYPE)
    VALUES (OLD.SOHD, OLD.NGHD, OLD.TRIGIA, 'DELETE');
END$$
DELIMITER ;
